// Login
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';
export const LOGIN_START_ERROR = 'LOGIN_START_ERROR';
//open Modal for recover Password
export const SET_FORGOT_PASSWORD_MODAL = 'SET_FORGOT_PASSWORD_MODAL';

//Countries API
export const GET_COUNTRIES = 'GET_COUNTRIES';

// Register
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_START_SUCCESS = 'REGISTER_START_SUCCESS';
export const REGISTER_START_ERROR = 'REGISTER_START_ERROR';

// Business
export const CONSULT_BUSINESS_SUCCESS = 'CONSULT_BUSINESS_SUCCESS';
export const CONSULT_BUSINESS_ERROR = 'CONSULT_BUSINESS_ERROR';

// User Business
export const SEARCH_USERBUSINESS_SUCCESS = 'SEARCH_USERBUSINESS_SUCCESS';
export const SEARCH_USERBUSINESS_ERROR = 'SEARCH_USERBUSINESS_ERROR';
export const SEARCH_USERBUSINESSPROFILE_SUCCESS = 'SEARCH_USERBUSINESSPROFILE_SUCCESS';
export const SEARCH_USERBUSINESSPROFILE_ERROR = 'SEARCH_USERBUSINESSPROFILE_ERROR';

// Register Querys
export const CONSULT_COUNTRIES_SUCCESS = 'CONSULT_COUNTRIES_SUCCESS';
export const CONSULT_COUNTRIES_ERROR = 'CONSULT_COUNTRIES_ERROR';

export const EDIT_OPEN = 'EDIT_OPEN';
export const EDIT_CLOSE = 'EDIT_CLOSE';

export const ADDADMIN_OPEN = 'ADDADMIN_OPEN';
export const ADDADMIN_CLOSE = 'ADDADMIN_CLOSE';

export const ADDPROFILE_OPEN = 'ADDPROFILE_OPEN';
export const ADDPROFILE_CLOSE = 'ADDPROFILE_CLOSE';

export const SAVE_OPEN = 'SAVE_OPEN';
export const SAVE_CLOSE = 'SAVE_CLOSE';

export const DELETE_OPEN = 'DELETE_OPEN';
export const DELETE_CLOSE = 'DELETE_CLOSE';

export const CLEAN_OPEN = 'CLEAN_OPEN';
export const CLEAN_CLOSE = 'CLEAN_CLOSE';

export const CLEAN_ON = 'CLEAN_ON';
export const CLEAN_OFF = 'CLEAN_OFF';

export const RUT_ON = 'RUT_ON';
export const RUT_CLOSE = 'RUT_CLOSE';

export const ADMINUSER_ON = 'ADMINUSER_ON';
export const ADMINUSER_CLOSE = 'ADMINUSER_CLOSE';

// Upload PDF's
export const UPLOADRUT_START_SUCCESS = 'UPLOADRUT_START_SUCCESS';
export const UPLOADRUT_START_ERROR = 'UPLOADRUT_START_ERROR';
export const UPLOADCCOMERCIO_START_SUCCESS = 'UPLOADCCOMERCIO_START_SUCCESS';
export const UPLOADCCOMERCIO_START_ERROR = 'UPLOADCCOMERCIO_START_ERROR';
export const UPLOADMMERCANTIL_START_SUCCESS = 'UPLOADMMERCANTIL_START_SUCCESS';
export const UPLOADMMERCANTIL_START_ERROR = 'UPLOADMMERCANTIL_START_ERROR';
//AdminUser
export const GET_BUSINESS = 'GET_BUSINESS';
export const GET_BUSINESS_STANDARD_DATA = 'GET_BUSINESS_STANDARD_DATA';
export const GET_BUSINESS_ADMIN_DATA = 'GET_BUSINESS_ADMIN_DATA';
export const SAVE_SELECTED_BUSINESS_DATA = 'SAVE_SELECTED_BUSINESS_DATA';
export const GET_USERS_BUSINESS_DATA = 'GET_USERS_BUSINESS_DATA';
export const GET_USERS_BUSINESS_BY_ID = 'GET_USERS_BUSINESS_BY_ID'
export const SAVE_FILTERED_USERS_BY_BUSINESS = 'SAVE_FILTERED_USERS_BUSINESS';
export const SAVE_CURRENT_USERDATA_SETTINGS = 'SAVE_CURRENT_USERDATA_SETTINGS';
export const SAVE_USER_SETTINGS_HISTORY = 'SAVE_USER_SETTINGS_HISTORY';
export const USER_SEARCH = 'USER_SEARCH';
export const DELETE_USER_ID = 'DELETE_USER_ID';
export const OPEN_CONFIRM_DELETE_DIALOG = 'OPEN_CONFIRM_DELETE_DIALOG';
export const CLOSE_CONFIRM_DELETE_DIALOG = 'CLOSE_CONFIRM_DELETE_DIALOG';
export const DISPLAY_UPDATE_BUTTON_ADMIN = 'DISPLAY_UPDATE_BUTTON_ADMIN';
export const DISPLAY_DELETE_ADMIN_BUTTON = 'DISPLAY_DELETE_ADMIN_BUTTON';
export const GET_UPDATE_ADMIN_STATE = 'GET_UPDATE_ADMIN_STATE';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const SET_UPD_ADM_CONFIRMATION = 'SET_UPD_ADM_CONFIRMATION';
//modules
export const GET_MODULES = 'GET_MODULES';
export const GET_USER_MODULES = 'GET_USER_MODULES';
export const FILTERED_USER_MODULES = 'FILTERED_USER_MODULES';
export const SAVE_USER_TYPE = 'SAVE_USER_TYPE';
export const SAVE_CURRENT_MODULES_DATA = 'SAVE_CURRENT_MODULES_DATA';
export const CREATE_USER_MODULES = 'CREATE_USER_MODULES';
export const SAVE_SWITCH_ADMIN_STATE_ACTION = 'SAVE_SWITCH_ADMIN_STATE_ACTION';
export const DELETE_PROFILE_MODULES = 'DELETE_PROFILE_MODULES';
export const OPEN_CONFIRM_DELETE_PROFILE_DIALOG = 'OPEN_CONFIRM_DELETE_PROFILE_DIALOG';
export const SET_MODULES_PROFILE = 'SET_MODULES_PROFILE';
export const ADMIN_USER_MODULES = 'ADMIN_USER_MODULES';
export const CLEAN_USER_PROFILE_MODULES_DATA = 'CLEAN_USER_PROFILE_MODULES_DATA';
export const UPDATE_MODULES = 'UPDATE_MODULES';
//wizard


/* export const EDIT_CLOSE = 'EDIT_CLOSE'; */

export const ADD_OPEN = 'ADD_OPEN';
export const ADD_CLOSE = 'ADD_CLOSE';
export const SEARCH_OPEN = 'SEARCH_OPEN';
export const SEARCH_CLOSE = 'SEARCH_CLOSE';

/* export const SAVE_OPEN = 'SAVE_OPEN';
export const SAVE_CLOSE = 'SAVE_CLOSE'; */

/* export const DELETE_OPEN = 'DELETE_OPEN';
export const DELETE_CLOSE = 'DELETE_CLOSE'; */

//export const CLEAN_OPEN = 'CLEAN_OPEN';
//export const CLEAN_CLOSE = 'CLEAN_CLOSE';

//export const CLEAN_ON = 'CLEAN_ON';
//export const CLEAN_OFF = 'CLEAN_OFF';

export const SON_OPEN = 'SON_OPEN';
export const SON_CLOSE = 'SON_CLOSE';